const default_data = {
    career: {
        job_title: 'Apotekare',
        salary: 35000,
        experience: 6
    },
    work_environment: {
        tags: [
            {id: 0, title: "Jämlikhet", active: false},
            {id: 1, title: "Hög ljudnivå", active: false},
            {id: 2, title: "Toppstyrt", active: false},
            {id: 3, title: "Övertid", active: false},
            {id: 4, title: "Transparens", active: false},
            {id: 5, title: "Miljöansvar", active: false},
            {id: 6, title: "Stor arbetsplats", active: false},
            {id: 7, title: "Hierarkiskt", active: false},
            {id: 8, title: "Mycket möten", active: false},
            {id: 9, title: "Bra löneläge", active: false},
            {id: 10, title: "God stämning", active: false},
            {id: 11, title: "Stressigt", active: false},
            {id: 12, title: "Konfliktfylld", active: false},
            {id: 13, title: "Utbildningsmöjligheter", active: false},
            {id: 14, title: "Öppetlandskap", active: false},
            {id: 15, title: "Mycket resor", active: false},
            {id: 16, title: "Liten arbetsplats", active: false},
            {id: 17, title: "Riskfyllt", active: false},
            {id: 18, title: "Kollektivavtal", active: false},
            {id: 19, title: "Hög sjukfrånvaro", active: false},
            {id: 20, title: "Många konsulter", active: false},
            {id: 21, title: "Fritidsaktiviteter", active: false},
            {id: 22, title: "Svår att ta föräldraledigt", active: false},
            {id: 23, title: "Utomhusarbete", active: false},
            {id: 24, title: "Inkluderande", active: false},
            {id: 25, title: "Träningsmöjligheter", active: false},
            {id: 26, title: "Samhällsansvar", active: false}
        ],
    },
    elected: {
		work_environment_value: 8,
		equality_value: 3,
		workplace_interest_value: 7,
		impact_value: 3,
		safe_workspace_value: 5
    },
    work_titles: [
		"Administratör",
		"Annonssäljare",
		"Apotekare",
		"Apoteksassistent",
		"Apotekschef",
		"Apotekstekniker",
		"Applikationsspecialist",
		"Art Director",
		"Besiktningstekniker (fordon)",
		"Beställare",
		"Butikschef (avdelningschef)",
		"CAD-ritare",
		"Controller",
		"Copywriter",
		"Drift- och underhållschef",
		"Drifttekniker IT",
		"Ekonom",
		"Ekonomiassistent",
		"Ekonomichef",
		"Fastighetsförvaltare",
		"Fastighetsmäklare",
		"Försäljningschef",
		"Grafisk formgivare/originalare",
		"Gruppchef",
		"Handläggare",
		"Hotellchef",
		"HR-chef",
		"HR-specialist",
		"Industridesigner",
		"Informationschef",
		"Informatör (kommunikatör)",
		"Ingenjör (tekniker)",
		"Inkassohandläggare",
		"Inköpare",
		"Inköps- och orderassistent",
		"Inköpschef",
		"Innesäljare",
		"Interaktionsdesigner",
		"IT-arkitekt",
		"IT-chef",
		"Jobbcoach",
		"Key account manager",
		"Kökschef",
		"Kommunikationschef",
		"Konstruktör (ingenjör)",
		"Kundtjänst",
		"Kundtjänst/Support (IT)",
		"Kvalitets- och miljöansvarig",
		"Kvalitets- och Miljöchef",
		"Kvalitetstekniker",
		"Laboratorieassistent",
		"Laboratorieingenjör",
		"Lager- och logistikchef",
		"Logistiker",
		"Löneadministratör",
		"Marknadsanalytiker",
		"Marknadsassistent",
		"Marknadschef",
		"Marknadsförare",
		"Marknadskoordinator",
		"Material- och produktionsplanerare",
		"Nätverkstekniker",
		"Orderbehandlare",
		"Personalchef",
		"Personalhandläggare",
		"Platschef (kontorchef, filialchef)",
		"Produktchef IT",
		"Produktionschef",
		"Produktionsledare",
		"Projektledare",
		"Projektledare IT (mindre)",
		"Projektledare IT (multipla)",
		"Receptarie",
		"Receptionist (kontor)",
		"Redovisningsekonom",
		"Resebyråchef",
		"Resesäljare",
		"Restaurangchef",
		"Revisor (extern)",
		"Revisorassistent (extern)",
		"Säkerhetschef",
		"Säljare",
		"Sekreterare (assistent)",
		"Serviceingenjör (tekniker)",
		"Speditör",
		"Supporttekniker IT",
		"Systemtestare IT",
		"Systemutvecklare",
		"Tandhygienist",
		"Tandsköterska",
		"Tandtekniker",
		"Teknikinformatör",
		"Telefonist",
		"Testledare (IT)",
		"Trafiklärare",
		"Transportplanerare",
		"Vaktmästare, kontorsservice",
		"Webbansvarig",
		"Webbredaktör",
		"Webbutvecklare (Webbdesigner)",
		"Mitt yrke saknas på listan"
		]
}

export default default_data;